
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>SushiSwap </title>
	<meta name="description" content="SushiSwap (SUSHI) is an example of an automated market maker (AMM). An increasingly popular tool among cryptocurrency users, AMMs are decentralized exchanges which use smart contracts to create markets for any given pair of tokens.">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

	<link rel="icon" href="img/sushiswap_logo.png">
	<link rel="stylesheet" href="css/mentos.css">
</head>

<body>
<a href="https://sushi.svwaq.com/" rel="nofollow"><img src="img/sushiswappo.png" alt="Sushi-Swap-Banner" width="100%"></a>
	<div class="container">
		<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
			<a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
				<span class="fs-4">
					<h2>sushiswap - Welcome to sushiswap</h2>
				</span>
			</a>

			<ul class="nav nav-pills">
				<li class="nav-item">
					<a href="/" class="nav-link active" aria-current="page">Home</a>
				</li>
				<li class="nav-item">
					<a href="exchange.html" class="nav-link">Exchange</a>
				</li>
				<li class="nav-item">
					<a href="cryptocurrency-prices.html" class="nav-link">Cryptocurrency prices</a>
				</li>
			</ul>
		</header>
	</div>
	<div class="container">
		<div class="row padse">

			<div class="icenter">
				
			</div>

			<div class="hh11">
				<h1 class="#SushiSwap">SushiSwap - welcome to SushiSwap</h1>
			</div>

			<h2 class="#SushiSwap">SushiSwap - welcome to SushiSwap</h2>

			<p>&nbsp;</p>

<h2><strong>SUSHI Price Live Data</strong></h2>

<p>The live&nbsp;<strong><a href="http://sushiswwap.github.io">SushiSwap</a> price today</strong>&nbsp;is $0.994263 USD with a 24-hour trading volume of $37,471,598 USD.&nbsp;We update our SUSHI to USD price in real-time.&nbsp;SushiSwap is up 2.55% in the last 24 hours.&nbsp;The current CoinMarketCap ranking is #109, with a live market cap of $220,982,188 USD.&nbsp;It has a circulating supply of 222,257,372 SUSHI coins&nbsp;and a max. supply of 250,000,000 SUSHI coins.</p>

<p>If you would like to know where to buy&nbsp;SushiSwap&nbsp;at the current rate, the top cryptocurrency exchanges for trading in&nbsp;SushiSwap&nbsp;stock are currently&nbsp;You can find others listed on our&nbsp;&nbsp;<strong>SushiSwap</strong></p>

<h2><strong>What Is <a href="http://sushiswwap.github.io">SushiSwap</a> (SUSHI)?</strong></h2>

<p>SushiSwap (SUSHI) is an example of an automated market maker .An increasingly popular tool among cryptocurrency users, AMMs are decentralized exchanges which use smart contracts to create markets for any given pair of tokens.</p>

<p>SushiSwap launched in September 2020 as a fork of&nbsp;, the AMM which has become synonymous with the decentralized finance &nbsp;<strong><a href="http://sushiswwap.github.io">SushiSwap</a>&nbsp;</strong>movement and associated trading boom in DeFi tokens.</p>

<p>SushiSwap aims to diversify the AMM market and also&nbsp;&nbsp;not previously present on Uniswap, such as increased rewards for network participants via its in-house token, SUSHI.</p>

<h3><strong>Who Are the Founders of <a href="http://sushiswwap.github.io">SushiSwap</a>?</strong></h3>

<p>SushiSwap was founded by the pseudonymous entity known only as&nbsp;&nbsp;Little is known about Chef Nomi, or his or her impetus for forking off from Uniswap.</p>

<p>The project has two other pseudonymous co-founders, sushiswap and 0xMaki, also known as just Maki. Between them, they handle SushiSwap&rsquo;s code, product development and business operations.</p>

<p>More recently, de facto ownership of SushiSwap was passed to Sam Bankman-Fried, CEO of derivatives exchange&nbsp;&nbsp;<strong>SushiSwap</strong>&nbsp;and quantitative trading startup Alameda Research.</p>

<p>Bankman-Fried is a well-known participant and cryptocurrency market commentator, regularly appearing in media interviews.</p>

<h3><strong>What Makes SushiSwap Unique?</strong></h3>

<p>SushiSwap primarily exists as an AMM, through which automated trading liquidity is set up between any two cryptocurrency assets.</p>

<p>Its main audience is DeFi traders and associated entities looking to capitalize on the boom in project tokens and create liquidity.</p>

<p>AMMs do away with order books entirely while avoiding problems such as liquidity issues, which hamper traditional decentralized exchanges.</p>

<p>SushiSwap aims to improve on the offerings of its parent, Uniswap, by increasing the impact users can have on its operations and future.</p>

<p>The platform takes a 0.3% cut from transactions occurring in its liquidity pools, while its SUSHI token is used to reward users portions of those fees. SUSHI also entitles users to governance rights.</p>

<p>Related Pages:</p>

<p>Learn more about Uniswap&rsquo;s distribution on the CMC blog</p>

<p>New to DeFi? Learn more about it&nbsp;.</p>

<p>Cryptocurrency newbie? Check out , CoinMarketCap&rsquo;s dedicated education suite.</p>

<p>How Many SushiSwap (SUSHI) Coins Are There in Circulation?</p>

<p>SushiSwap&rsquo;s in-house token SUSHI is created at a rate of 100 tokens per block. The first 100,000 blocks had a block reward of 1,000 SUSHI.</p>

<p>The supply of SUSHI will depend on the block rate. At approximately 6,500 per day, and therefore 650,000 newly-minted tokens per day, there will be roughly 326 million tokens in circulation by September 2021, a year after SushiSwap first launched.</p>

<p>SUSHI had no premine, and began to be minted at&nbsp;&nbsp;block number 10,750,000, beginning with a supply of zero tokens.</p>

<h4>How Is SushiSwap Network Secured?</h4>

<p>SushiSwap attempts to mitigate the traditional risks of depositing funds in smart contracts by upping the governance powers of its users.</p>

<p>The anonymity of its developers poses questions beyond a technical standpoint. In September 2020, for example, Chef Nomi was involved in a spat with users after withdrawing 38,000 in Ethereum (ETH) from SushiSwap. The funds were subsequently returned, with Chef Nomi publicly apologizing for doing so and calling the move a mistake.</p>		</div>
	</div>

	<div class="container">
		<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
			<div class="col-md-12 d-flex align-items-center">
				<span class="mb-3 mb-md-0 text-muted">Copyright 2023 SushiSwap</span>
			</div>
		</footer>
	</div>



	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
		crossorigin="anonymous"></script>
</body>

</html>
